### ISSUE TITLE
Contract has not been deployed... alway got this 

### ISSUE THREAD

**Issue by Nakinthorn** [Vitalik-Hakim/NFT-sale#1]
Thank you for your share the code of NFT
btw, every time i try to click on purchase button it alway printout the message:  Contract has not been deployed....
So, how to fixed it ?

and if i need to use SmartBCH instead of ETH how i can do

thank for ur reply

**Comment by Vitalik-Hakim** [comment]
I just updated the Readme, check and see.  If it solves the problem.
Make sure to compile and test the contracts.
Hope This helps
